config/routes.rb
Rails.application.routes.draw do
  get 'tricks/show'

  get 'tricks/new'

  get 'tricks/create'

  get 'tricks/destroy'

  get 'favorites/create'

  get 'favorites/destroy'

  get 'relationships/new'

  get 'relationships/create'

  get 'relationships/destroy'

  get 'genres/index'

  get 'genres/show'

  get 'genres/new'

  get 'genres/create'

  get 'genres/destroy'

  get 'videos/show'

  get 'videos/new'

  get 'videos/create'

  get 'memos/new'

  get 'memos/create'

  get 'memos/destroy'

  get 'sessions/new'

  get 'sessions/create'

  get 'sessions/destroy'

  get 'users/show'

  get 'users/new'

  get 'users/create'

  get 'toppages/index'

  root to: "toppages#index"

 


  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  get 'signup', to: 'users#new'
  resources :users, only: [:index, :show, :new, :create, :update, :edit] do
  member do
      get :library
    end
  end


  resources :memos, only: [:index, :new, :create, :destroy, :edit, :update]


  get 'option', to: 'genres#option'

  resources :genres, only: [:index, :show, :new, :create, :destroy] do
  member do
      get :select
      post :trickcreate
    end
  end

  resources :tricks, only: [:show, :new, :create, :destroy]

  resources :videos, only: [:index, :show, :new, :create, :destroy]

  resources :relationships, only: [:new, :create, :destroy]

  resources :favorites, only: [:create, :destroy]

   get 'add', to: 'memos#new'
end

app/models/genre.rb
class Genre < ApplicationRecord
  validates :name, presence: true, length: { maximum: 50 }


  has_many :relationships
  has_many :clips, through: :relationships, source: :video

  has_many :tricks

   def self.search(search) #self.でクラスメソッドとしている
    if search # Controllerから渡されたパラメータが!= nilの場合は、titleカラムを部分一致検索
      Genre.where(['name LIKE ?', "%#{search}%"])
    else
      Genre.all #全て表示。
    end
   end
end

app/controllers/genres_controller.rb
class GenresController < ApplicationController
 before_action :require_user_logged_in

  def index
    @genres = Genre.search(params[:search])
  end

  def show
    @genres = Genre.all
    @genre = Genre.find(params[:id])
    @videos = @genre.clips.order('created_at DESC').page(params[:page])
    @count_clips = Video.all.count
  end

  def new
    @genre = Genre.new
  end

  def create
    @genre = Genre.new(genre_params)
    if @genre.save
      flash[:success] = '新ジャンルを登録しました。'
      redirect_to root_url
    else
      flash.now[:danger] = '新ジャンルの登録に失敗しました。'
      render :new
    end
  end

  def destroy
  end

  def option
    @genres = Genre.all
  end

  def select
    @genre = Genre.find(params[:id])
    @trick = Trick.new
  end

  def trickcreate
    genre = Genre.find(params[:id])
    trick = genre.tricks.build(trick_params)
    if trick.save
    flash[:success] = '新トリックを登録しました。'
      redirect_to root_url
    else
      flash[:danger] = '新トリックの登録に失敗しました。'
      redirect_to select_genre_path
    end
  end

  private

  def genre_params
    params.require(:genre).permit(:name)
  end

  def trick_params
    params.require(:trick).permit(:name)
  end
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/views/genres/index.html.erb
<div class="text-center icon_caption">
  <span class="glyphicon glyphicon-search color-black" style="font-size: 30px"></span>
    <p class = "text">SEARCH</p>
</div>

<div class="hidden-xs">
    <div class="center-item">
        <div>
            <img src="../../images/flatground.jpg" width="350" height="200">
            <p class="caption">FLATGROUND TRICKS</p>
        </div>

        <div>
            <img src="../../images/ledge.jpg" width="350" height="200">
            <p class="caption">LEDGE</p>
        </div>

        <div>
            <img src="../../images/clip.png" width="350" height="200">
            <p class="caption">CLIP OF THE DAY</p>
        </div>

        <div>
            <img src="../../images/rail.jpg" width="350" height="200">
            <p class="caption">RAILS</p>
        </div>

        <div>
          <img src="../../images/stairs.jpg" width="350" height="200">
          <p class="caption">STAIRS</p>
        </div>
    </div>
</div>

<div class="visible-xs">
    <div class="center-item">
        <div>
            <img src="../../images/flatground.jpg" width="200" height="100">
            <p class="caption">FLATGROUND TRICKS</p>
        </div>

        <div>
            <img src="../../images/ledge.jpg" width="200" height="100">
            <p class="caption">LEDGE</p>
        </div>

        <div>
            <img src="../../images/clip.png" width="200" height="100">
            <p class="caption">CLIP OF THE DAY</p>
        </div>

        <div>
            <img src="../../images/rail.jpg" width="200" height="100">
            <p class="caption">RAILS</p>
        </div>

        <div>
          <img src="../../images/stairs.jpg" width="200" height="100">
          <p class="caption">STAIRS</p>
        </div>
    </div>
</div>

<div class= "form1">
    <div class="col-xs-12 col-lg-6">
        <p>トリック検索</p>
        <div class="form-group">
            <%= form_tag(genres_path,:method => 'get') do %>
                <%= text_field_tag :search %>
                <%= submit_tag 'Search', :name => nil %>
            <% end %>
        </div>
        <ul>
            <% @genres.each do |genre| %>
                <li>
                    <%= link_to genre.name, genre %>
                </li>
            <% end %>
        </ul>
    </div>
</div>

app/views/genres/new.html.erb
<div class="row">
    <div class="col-xs-12 col-lg-offset-3 col-lg-6">
        <div class="panel panel-default">
            <div class="panel-heading">ジャンルを新規作成</div>
                <div class="panel-body">
                    <%= form_for(@genre) do |f| %>

                    <% if @genre.errors.any? %>
                      <div class="alert alert-warning">
                        <div id="error_explanation">
                          <ul>
                            <% @genre.errors.full_messages.each do |message| %>
                              <li><%= message %></li>
                            <% end %>
                          </ul>
                        </div>
                      </div>
                    <% end %>

                    <div class="form-group">
                        <%= f.label :name, 'ジャンル名' %>
                        <%= f.text_field :name, class: 'form-control' %>
                    </div>

                    <div class="text-right">
                        <%= f.submit '追加する', class: 'btn btn-success btn-block' %>
                    </div>
                    <% end %>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/genres/option.html.erb
<div class="text-center">
    <div class="row">
        <div class="col-xs-12 col-lg-offset-3 col-lg-6">
            <div class="panel panel-default">
                <div class= "panel-heading">どのジャンルに属するトリックを作成しますか？</div>
                <div class="panel-body">

                    <ul class="media-list">
                        <% @genres.each do |genre| %>
                        <li class="back">
                            <%= link_to genre.name, select_genre_path(genre.id) %>
                        </li>
                        <% end %>
                    </ul>
                    <div>
                        <%= link_to root_path do %><span class="glyphicon glyphicon-chevron-left"　aria-hidden="true">戻る</span><% end %>
                        <%= link_to new_genre_path, class: 'btn btn-success btn-lg' do %><span class="glyphicon glyphicon-plus">ジャンルを追加する</span><% end %>
                    </div>       
                </div>
            </div>
        </div>
    </div>
</div>

app/views/genres/select.html.erb
<div class= "text-center">
    <h1>選択したジャンル: <%= @genre.name %></h1>
</div>

<div class="row">
    <div class="col-xs-12 col-lg-offset-3 col-lg-6">
        <div class="panel panel-default">
            <div class="panel-heading">トリックを新規作成</div>
            <div class="panel-body">
                <%= form_for(@trick, url: trickcreate_genre_path(@genre.id)) do |f| %>

                <% if @trick.errors.any? %>
                  <div class="alert alert-warning">
                    <div id="error_explanation">
                      <ul>
                        <% @trick.errors.full_messages.each do |message| %>
                          <li><%= message %></li>
                        <% end %>
                      </ul>
                    </div>
                  </div>
                <% end %>

                <div class="form-group">
                    <%= f.label :name, 'トリック名' %>
                    <%= f.text_field :name, class: 'form-control' %>
                </div>
                <div class="text-right">
                    <%= f.submit '追加する', class: 'btn btn-success btn-block' %>
                </div>
                <% end %>
                    <%= link_to option_path do %><span class="glyphicon glyphicon-chevron-left"　aria-hidden="true">戻る</span><% end %>
            </div>
        </div>
    </div>
</div>

app/views/genres/show.html.erb
<div class="hidden-xs">
    <div class="center-item">
        <div>
            <img src="../../images/flatground.jpg" width="350" height="200">
            <p class="caption">FLATGROUND TRICKS</p>
        </div>

        <div>
            <img src="../../images/ledge.jpg" width="350" height="200">
            <p class="caption">LEDGE</p>
        </div>

        <div>
            <img src="../../images/clip.png" width="350" height="200">
            <p class="caption">CLIP OF THE DAY</p>
        </div>

        <div>
            <img src="../../images/rail.jpg" width="350" height="200">
            <p class="caption">RAILS</p>
        </div>

        <div>
            <img src="../../images/stairs.jpg" width="350" height="200">
            <p class="caption">STAIRS</p>
        </div>
    </div>

    <nav class="navbar  navbar-inverce">
        <ul class="nav nav-tabs nav-justified">
            <li class="<%= 'active' if current_page?(root_path) %>"><%= link_to root_path do %>CLIP OF THE DAY <span class="badge"><%= @count_clips %></span><% end %></li>
            <% @genres.each do |genre| %>
            <li class="<%= 'active' if current_page?(genre_path(genre.id)) %>"><%= link_to genre_path(genre.id) do %><%= genre.name %> <span class="badge"><%= genre.clips.count %></span><% end %></li>
            <% end %>
        </ul>
    </nav>

    <% @genre.tricks.each do  |trick| %>
    <nav class="navbar  navbar-inverce">
        <ul class="nav nav-tabs nav-justified">
            <li class="<%= 'active' if current_page?(trick_path(trick.id)) %>"><%= link_to trick_path(trick.id) do %><%= trick.name %><span class="badge"><%= trick.clips.count %></span><% end %></li>
        </ul>
    </nav>
    <% end %>

    <ul class="media-list">
        <% @videos.each do |video| %>
        <%#= video.inspect %>
        <div class="text-center">
            <div>
                <iframe width="560" height="315" src="<%= video.iframe_url %>;modestbranding=1;end=7;rel=0&autoplay=<0></0>" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen"></iframe>
            </div>

            <div>
                <%= render 'favorites/like_button', video: video %><span class="badge"><%= video.favorites.count %></span>
            </div>

            <div class="details">
                <p><%= video.trick %></p>
            </div>

            <div class="details">
                <p><%= video.skater %></p>
            </div>

            <div class="details">
            <p><%= video.instagram_url %></p>
            </div>

            <div class="details">
                <p><%= video.video_url %></p>
            </div>
        </div>
        <% end %>
    </ul>
</div>

<div class="visible-xs">
    <div class="center-item">
        <div>
            <img src="../../images/flatground.jpg" width="200" height="100">
            <p class="caption">FLATGROUND TRICKS</p>
        </div>

        <div>
            <img src="../../images/ledge.jpg" width="200" height="100">
            <p class="caption">LEDGE</p>
        </div>

        <div>
            <img src="../../images/clip.png" width="200" height="100">
            <p class="caption">CLIP OF THE DAY</p>
        </div>

        <div>
            <img src="../../images/rail.jpg" width="200" height="100">
            <p class="caption">RAILS</p>
        </div>

        <div>
            <img src="../../images/stairs.jpg" width="200" height="100">
            <p class="caption">STAIRS</p>
        </div>
    </div>

    <nav class="navbar  navbar-inverce">
        <ul class="nav nav-tabs nav-justified">
            <li class="<%= 'active' if current_page?(root_path) %>"><%= link_to root_path do %>CLIP OF THE DAY <span class="badge"><%= @count_clips %></span><% end %></li>
            <% @genres.each do |genre| %>
            <li class="<%= 'active' if current_page?(genre_path(genre.id)) %>"><%= link_to genre_path(genre.id) do %><%= genre.name %> <span class="badge"><%= genre.clips.count %></span><% end %></li>
            <% end %>
        </ul>
    </nav>

    <% @genre.tricks.each do  |trick| %>
    <nav class="navbar  navbar-inverce">
        <ul class="nav nav-tabs nav-justified">
            <li class="<%= 'active' if current_page?(trick_path(trick.id)) %>"><%= link_to trick_path(trick.id) do %><%= trick.name %><span class="badge"><%= trick.clips.count %></span><% end %></li>
        </ul>
    </nav>
    <% end %>

    <ul class="media-list">
        <% @videos.each do |video| %>
        <%#= video.inspect %>
        <div class="text-center">
            <div>
                <iframe width="100%" height="194" src="<%= video.iframe_url %>;modestbranding=1;end=7;rel=0&autoplay=<0></0>" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen"></iframe>
            </div>

            <div>
                <%= render 'favorites/like_button', video: video %><span class="badge"><%= video.favorites.count %></span>
            </div>

            <div class="details">
                <p><%= video.trick %></p>
            </div>

            <div class="details">
                <p><%= video.skater %></p>
            </div>

            <div class="details">
                <p><%= video.instagram_url %></p>
            </div>

            <div class="details">
                <%= video.video_url %>
            </div>
        </div>
        <% end %>
    </ul>
</div>