config/routes.rb
Rails.application.routes.draw do
  get 'tricks/show'

  get 'tricks/new'

  get 'tricks/create'

  get 'tricks/destroy'

  get 'favorites/create'

  get 'favorites/destroy'

  get 'relationships/new'

  get 'relationships/create'

  get 'relationships/destroy'

  get 'genres/index'

  get 'genres/show'

  get 'genres/new'

  get 'genres/create'

  get 'genres/destroy'

  get 'videos/show'

  get 'videos/new'

  get 'videos/create'

  get 'memos/new'

  get 'memos/create'

  get 'memos/destroy'

  get 'sessions/new'

  get 'sessions/create'

  get 'sessions/destroy'

  get 'users/show'

  get 'users/new'

  get 'users/create'

  get 'toppages/index'

  root to: "toppages#index"

 


  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  get 'signup', to: 'users#new'
  resources :users, only: [:index, :show, :new, :create, :update, :edit] do
  member do
      get :library
    end
  end


  resources :memos, only: [:index, :new, :create, :destroy, :edit, :update]


  get 'option', to: 'genres#option'

  resources :genres, only: [:index, :show, :new, :create, :destroy] do
  member do
      get :select
      post :trickcreate
    end
  end

  resources :tricks, only: [:show, :new, :create, :destroy]

  resources :videos, only: [:index, :show, :new, :create, :destroy]

  resources :relationships, only: [:new, :create, :destroy]

  resources :favorites, only: [:create, :destroy]

   get 'add', to: 'memos#new'
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email.downcase! }
  validates :name, presence: true, length: { maximum: 50 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                    uniqueness: { case_sensitive: false }
    has_secure_password
    
    has_many :memos
    
    has_many :favorites
    has_many :liked, through: :favorites, source: :video
    
    def like(other_video)
      self.favorites.find_or_create_by(video_id: other_video.id)
    end

    def unlike(other_video)
      favorite = self.favorites.find_by(video_id: other_video.id)
      favorite.destroy if favorite
    end

    def liking?(other_video)
      self.liked.include?(other_video)
    end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_user_logged_in, only: [:show]

  def index
    @users = User.all
    @user = current_user
  end
  def show
    @user = User.find(params[:id])
    @memo = current_user.memos.build
    @memos = @user.memos.order('created_at DESC').page(params[:page])
  end

  def new
    @user = User.new
  end

  def create
     @user = User.new(
       name: user_params[:name],
       email: user_params[:email],
       password: user_params[:password],
       image_name: "default_user.jpg"
     )

    if @user.save
      flash[:success] = 'ユーザを登録しました。'
      redirect_to @user
    else
      flash.now[:danger] = 'ユーザの登録に失敗しました。'
      render :new
    end
  end

  def edit
    @user = User.find_by(id: params[:id])
  end

  def update
    @user = User.find_by(id: params[:id])
    @user.name = user_params[:name]
    @user.email = user_params[:email]

    if user_params[:image_name]
      @user.image_name = "#{@user.id}.jpg"
      image = user_params[:image_name]
      File.binwrite("public/user_images/#{@user.image_name}", image.read)
    end

    if @user.save
      flash[:success] = "ユーザー情報を編集しました"
      redirect_to current_user
    else
      render edit
    end
  end


  def library
    @user = User.find(params[:id])
    @liked = @user.liked.page(params[:page])
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :image_name, :password_confirmation)
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_url(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}&d=mp"
  end
end

app/views/users/drop.html.erb
<div class="user-profile">
    <div class="icon text-center">
        <img src="<%= gravatar_url(@user, size: 100) %>" alt="" class="img-circle">
    </div>

    <div class="name text-center">
        <h1><%= @user.name %></h1>
    </div>
</div>

 <%= render 'memos/memos', memos: @memos %>

app/views/users/edit.html.erb
<div class="users-edit">
  <div class="container">
    <div class="form-heading text-center">アカウント編集</div>
    <div class="form users-form">
      <div class="form-body">
        <% @user.errors.full_messages.each do |message| %>
          <div class="form-error">
            <%= message %>
          </div>
        <% end %>



        <%= form_for(@user) do |f| %>
          <%= f.label :name, 'ユーザー名' %>
          <%= f.text_field :name %>

          <%= f.label :image_name, 'プロフィール画像' %>
          <%= f.file_field :image_name %>

          <%= f.label :content, 'メール' %>
          <%= f.text_field :email %>

          <%= f.submit '更新' %>
        <% end %>

      </div>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="users-index">
    <ul class="user-tabs">
      <li class><%= link_to "投稿", user_path(current_user.id) %></li>
      <li class="active"><%= link_to "ユーザー", users_path %></li>
      <li class><%= link_to "フィード", memos_path %></li>
    </ul>

    <% @users.each do |user| %>
      <div class="users-index-item">
        <div class="user-left">
          <img src="<%= "/user_images/#{user.image_name}" %>">
        </div>
        <div class="user-right">
          <%= link_to user.name, user_path(user.id) %>
        </div>
      </div>
    <% end %>
</div>

app/views/users/library.html.erb
<div class="text-center icon_caption">
  <span class="glyphicon glyphicon-bookmark color-black" style="font-size: 30px"></span>
    <p class = "text">FAVORITES</p>
</div>

<%= render 'videos/videos', videos: @liked %>

app/views/users/new.html.erb
<div class="row">
    <div class="col-xs-12 col-lg-offset-3 col-lg-6">
        <div class="panel panel-default">
            <div class="panel-heading">ユーザー登録</div>
            <div class="panel-body">

                <%= form_for(@user) do |f| %>

                  <% if @user.errors.any? %>
                    <div class="alert alert-warning">
                      <div id="error_explanation">
                        <ul>
                          <% @user.errors.full_messages.each do |message| %>
                            <li><%= message %></li>
                          <% end %>
                        </ul>
                      </div>
                    </div>
                  <% end %>

                    <div class="form-group">
                        <%= f.label :name, 'お名前' %>
                        <%= f.text_field :name, class: 'form-control' %>
                    </div>

                    <div class="form-group">
                        <%= f.label :email, 'メールアドレス' %>
                        <%= f.email_field :email, class: 'form-control' %>
                    </div>

                    <div class="form-group">
                        <%= f.label :password, 'パスワード' %>
                        <%= f.password_field :password, class: 'form-control' %>
                    </div>

                    <div class="form-group">
                        <%= f.label :password_confirmation, 'パスワード（確認）' %>
                        <%= f.password_field :password_confirmation, class: 'form-control' %>
                    </div>

                    <div class="text-right">
                        <%= f.submit '登録する', class: 'btn btn-success' %>
                    </div>
                <% end %>

            </div>
        </div>
    </div>
</div>

app/views/users/show.html.erb
<div class="memo-modal-wrapper" id="memo-modal">
    <div class="moda">
        <div class="close-modal">
            <i class="fa fa-2x fa-times"></i>
        </div>

    <div id="memo-form">
        <h1><span class="fa fa-pencil">新規投稿</span></h1>

        <%= form_for(@memo) do |f| %>
            <div class="form-group">
                <%= f.text_field :trick, class: 'form-control', :placeholder => "トリック名" %>
            </div>

            <div class="form-group">
                <%= f.text_area :content, class: 'form-control', rows: 4, :placeholder => "コツ" %>
            </div>
    </div>
            <div class = "text-center">
                <%= f.submit 'POST', id: 'memo-submit-btn' %>
            </div>
        <% end %>
    </div>
</div>

<div class="user-show">
    <div class="user">
      <img src="<%= "/user_images/#{@user.image_name}" %>">

      <h2><%= @user.name %></h2>
      <p><%= @user.email %></p>
      <% if @user.id == @current_user.id %>
        <%= link_to("編集", edit_user_path(@user.id)) %>
      <% end %>
    </div>

    <ul class="user-tabs">
      <li class="active"><%= link_to "投稿", user_path(current_user.id) %></li>
      <li class><%= link_to "ユーザー", users_path %></li>
      <li class><%= link_to "フィード", memos_path %></li>
    </ul>

    <% @user.memos.each do |memo| %>
      <div class="memos-index-item">
        <div class="memo-left">
           <img src="<%= "/user_images/#{memo.user.image_name}" %>">
        </div>
        <div class="memo-right">
          <div class="memo-user-name">
            <%= link_to memo.trick, user_path(memo.user) %>
          </div>
          <%= link_to memo.content, user_path(memo.user) %>
        </div>
         <div class="delete-memo">
          <% if current_user == memo.user %>
              <%= link_to memo, method: :delete, data: { confirm: "You sure?" } do %> <span class="glyphicon glyphicon-trash color-black" style="font-size: 25px"></span><% end %>
          <% end %>
          <% if current_user == memo.user %>
              <%= link_to edit_memo_path(memo.id) do %> <span class="glyphicon glyphicon-pencil color-black" style="font-size: 25px"></span><% end %>
          <% end %>
        </div>
      </div>
    <% end %>
    <% if current_user == @user %>
        <div><span class="fa fa-plus memo-show" style="font-size: 30px"></span></div>
    <% end %>
</div>






<script>
$('h1').fadeIn(3000);
</script>

<script>
$('section').fadeIn(2000);
</script>

<script>
$('p').fadeIn(4500);
</script>