config/routes.rb
Rails.application.routes.draw do
  get 'tricks/show'

  get 'tricks/new'

  get 'tricks/create'

  get 'tricks/destroy'

  get 'favorites/create'

  get 'favorites/destroy'

  get 'relationships/new'

  get 'relationships/create'

  get 'relationships/destroy'

  get 'genres/index'

  get 'genres/show'

  get 'genres/new'

  get 'genres/create'

  get 'genres/destroy'

  get 'videos/show'

  get 'videos/new'

  get 'videos/create'

  get 'memos/new'

  get 'memos/create'

  get 'memos/destroy'

  get 'sessions/new'

  get 'sessions/create'

  get 'sessions/destroy'

  get 'users/show'

  get 'users/new'

  get 'users/create'

  get 'toppages/index'

  root to: "toppages#index"

 


  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  get 'signup', to: 'users#new'
  resources :users, only: [:index, :show, :new, :create, :update, :edit] do
  member do
      get :library
    end
  end


  resources :memos, only: [:index, :new, :create, :destroy, :edit, :update]


  get 'option', to: 'genres#option'

  resources :genres, only: [:index, :show, :new, :create, :destroy] do
  member do
      get :select
      post :trickcreate
    end
  end

  resources :tricks, only: [:show, :new, :create, :destroy]

  resources :videos, only: [:index, :show, :new, :create, :destroy]

  resources :relationships, only: [:new, :create, :destroy]

  resources :favorites, only: [:create, :destroy]

   get 'add', to: 'memos#new'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/connection.rb
class Connection < ApplicationRecord
  belongs_to :trick
  belongs_to :video
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :video
end

app/models/genre.rb
class Genre < ApplicationRecord
  validates :name, presence: true, length: { maximum: 50 }


  has_many :relationships
  has_many :clips, through: :relationships, source: :video

  has_many :tricks

   def self.search(search) #self.でクラスメソッドとしている
    if search # Controllerから渡されたパラメータが!= nilの場合は、titleカラムを部分一致検索
      Genre.where(['name LIKE ?', "%#{search}%"])
    else
      Genre.all #全て表示。
    end
   end
end

app/models/memo.rb
class Memo < ApplicationRecord
    validates :trick, presence: true, length: { maximum: 50 }
    validates :content, presence: true, length: { maximum: 100 }
    
    
  belongs_to :user
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :genre
  belongs_to :video
end

app/models/trick.rb
class Trick < ApplicationRecord
  validates :name, presence: true, length: { maximum: 50 }
  
  belongs_to :genre

  has_many :connections
  has_many :clips, through: :connections, source: :video
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email.downcase! }
  validates :name, presence: true, length: { maximum: 50 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                    uniqueness: { case_sensitive: false }
    has_secure_password
    
    has_many :memos
    
    has_many :favorites
    has_many :liked, through: :favorites, source: :video
    
    def like(other_video)
      self.favorites.find_or_create_by(video_id: other_video.id)
    end

    def unlike(other_video)
      favorite = self.favorites.find_by(video_id: other_video.id)
      favorite.destroy if favorite
    end

    def liking?(other_video)
      self.liked.include?(other_video)
    end
  
end

app/models/video.rb
class Video < ApplicationRecord
  validates :iframe_url, presence: true, length: { maximum: 255 }
  validates :skater, presence: true, length: { maximum: 255 }
  validates :trick, presence: true, length: { maximum: 255 }
  validates :instagram_url, length: { maximum: 255 }
  validates :video_url, presence: true, length: { maximum: 255 }
  validates :video_type, presence: true, length: { maximum: 255 }

  has_many :relationships
  has_many :types, through: :relationships, source: :genre

  has_many :connections
  has_many :names, through: :connections, source: :trick

  has_many :favorites
  has_many :likes, through: :favorites, source: :user


  def belong(group)
    self.relationships.find_or_create_by(genre_id: group.id)
  end
end

app/controllers/memos_controller.rb
class MemosController < ApplicationController
  before_action :require_user_logged_in
  before_action :correct_user, only: [:destroy]


  def index
      @memos = Memo.all.order('created_at DESC').page(params[:page])
      @memo = current_user.memos.build
      @user = current_user
  end

  def new
      @memo = current_user.memos.build  # form_for 用
      @memos = current_user.memos.order('created_at DESC').page(params[:page])
  end

  def create
    @user = current_user
    @memo = current_user.memos.build(memo_params)
    if @memo.save
      flash[:success] = 'メモを追加しました。'
      redirect_back(fallback_location: root_path)
    else
      @memos = current_user.memos.order('created_at DESC').page(params[:page])
      flash.now[:danger] = 'メモの追加に失敗しました。'
      render 'memos/new'
    end
  end

  def destroy
    @memo.destroy
    flash[:danger] = 'メモを削除しました。'
    redirect_back(fallback_location: root_path)
  end

  def edit
    @memo = Memo.find(params[:id])
  end

  def update
    @memo = Memo.find(params[:id])

    if @memo.update(memo_params)
      flash[:success] = 'メモは正常に更新されました'
      redirect_to current_user
    else
      flash.now[:danger] = 'メモは更新されませんでした'
      render :edit
    end
  end

   private

  def memo_params
    params.require(:memo).permit(:trick, :content)
  end

  def correct_user
    @memo = current_user.memos.find_by(id: params[:id])
    unless @memo
      redirect_to root_url
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_user_logged_in, only: [:show]

  def index
    @users = User.all
    @user = current_user
  end
  def show
    @user = User.find(params[:id])
    @memo = current_user.memos.build
    @memos = @user.memos.order('created_at DESC').page(params[:page])
  end

  def new
    @user = User.new
  end

  def create
     @user = User.new(
       name: user_params[:name],
       email: user_params[:email],
       password: user_params[:password],
       image_name: "default_user.jpg"
     )

    if @user.save
      flash[:success] = 'ユーザを登録しました。'
      redirect_to @user
    else
      flash.now[:danger] = 'ユーザの登録に失敗しました。'
      render :new
    end
  end

  def edit
    @user = User.find_by(id: params[:id])
  end

  def update
    @user = User.find_by(id: params[:id])
    @user.name = user_params[:name]
    @user.email = user_params[:email]

    if user_params[:image_name]
      @user.image_name = "#{@user.id}.jpg"
      image = user_params[:image_name]
      File.binwrite("public/user_images/#{@user.image_name}", image.read)
    end

    if @user.save
      flash[:success] = "ユーザー情報を編集しました"
      redirect_to current_user
    else
      render edit
    end
  end


  def library
    @user = User.find(params[:id])
    @liked = @user.liked.page(params[:page])
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :image_name, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/memos_helper.rb
module MemosHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
    
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !!current_user
  end
end

app/helpers/toppages_helper.rb
module ToppagesHelper
end

app/helpers/tricks_helper.rb
module TricksHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_url(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}&d=mp"
  end
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/layouts/_flash_messages.html.erb
<% flash.each do |message_type, message| %>
    <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>

app/views/layouts/_footer.html.erb
<footer>
    <% if logged_in? %>

        <nav class="navbar navbar-default navbar-fixed-bottom">
            <div class="container">


                <div class="icon icon-home">
                   <%= link_to root_url do %><span class="glyphicon glyphicon-home color-black" style="font-size: 30px"></span><% end %>
                </div>

                <div class="icon icon-search">
                    <%= link_to genres_path do %><span class="glyphicon glyphicon-search color-black" style="font-size: 30px"></span><% end %>
                </div>

                <div class="icon icon-library">
                    <%= link_to library_user_path(current_user) do %><span class="glyphicon glyphicon-bookmark color-black" style="font-size: 30px"></span><% end %>
                </div>

                <div class="icon icon-user">
                    <%= link_to current_user do %><span class="glyphicon glyphicon-user color-black" style="font-size: 30px"></span><% end %>
                </div>
            </div>

        </nav>

   <% else %>
       <div class="bottom">
           <div class="text-center text-muted">© 2019 PEBBLE SKATE JAPAN.</div>
       <div>
   <% end %>
</footer>

app/views/layouts/_navbar.html.erb
<header>
    <nav class="navbar navbar-default navbar-static-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-left" href="/"><img src="/images/pebblelogo.png"  alt="SKATE CLIPS"></a>
                <a class="navbar-left" href="https://www.instagram.com/pebbleskateclips/"><img src="/images/instagram.png"  alt="SKATE CLIPS"></a>
            </div>
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                    <% if logged_in? %>

                        <li>
                            <%= link_to genres_path do %><span class="glyphicon glyphicon-search"　aria-hidden="true">検索</span><% end %>
                        </li>

                        <li>
                            <%= link_to option_path do %><span class="glyphicon glyphicon-plus"　aria-hidden="true">トリックを作成する</span><% end %>
                        </li>

                        <li>
                            <%= link_to new_genre_path do %><span class="glyphicon glyphicon-plus"　aria-hidden="true">ジャンルを作成する</span><% end %>
                        </li>

                        <li>
                            <%= link_to new_video_path do %><span class="glyphicon glyphicon-plus"　aria-hidden="true">動画を投稿する</span><% end %>
                        </li>

                        <li class="dropdown">
                            <a href="" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                            <span class="gravatar">
                                <img src="<%= "/user_images/#{current_user.image_name}" %>" alt="" class="img-circle nav_profile_image">
                            </span>
                                <%= current_user.name %>
                            <span class="caret"></span>
                            </a>
                            <ul class="dropdown-menu">
                                <li>
                                    <%= link_to 'マイページ', user_path(current_user) %>
                                </li>
                                <li role="separator" class="divider"></li>
                                <li>
                                    <%= link_to 'ログアウト', logout_path, method: :delete %>
                                </li>
                            </ul>
                        </li>

                    <% else %>

                        <li><%= link_to '新規登録', signup_path %></li>
                        <li><%= link_to 'ログイン', login_path %></li>

                    <% end %>
                </ul>
            </div>
        </div>
    </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <title>SKATE CLIPS</title>
        <%= csrf_meta_tags %>

         <%# Bootstrap CSS--> %>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">

        <%#  app/assets/stylesheets  %>
        <%= stylesheet_link_tag  'application', media: 'all', 'data-turbolinks-track': 'reload' %>

         <%# app/assets/javascripts--> %>

        <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
      
        <%# Bootstrap JavaScript--> %>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>


        <%# <!--<link rel="stylesheet" type="text/css" href="/assets/slick.css" media="screen" />--> %>
        <%# <!--<link rel="stylesheet" type="text/css" href="/assets/slick-theme.css" media="screen" />--> %>



    </head>

    <body>
        <%= render 'layouts/navbar' %>

        <%= yield :cover %>

        <div class="container">
            <%= render 'layouts/flash_messages' %>
            <%= yield %>
        </div>

      <%= render 'layouts/footer' %>
    </body>
</html>